environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "html"
    - PYTHON: "C:\\Python36"
      TOXENV: "linkcheck"

cache:
    - '%LOCALAPPDATA%\pip\Cache'

version: '{branch}.{build}'

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\Scripts\\tox.exe"
